# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horactual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='superheroe',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='SuperHeroe',
        ),
    ]
