# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horactual', '0002_auto_20170526_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechahora',
            name='tiempo',
            field=models.CharField(default=datetime.datetime(2017, 5, 26, 22, 21, 4, 989000), max_length=200),
        ),
    ]
