# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 20:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horactual', '0003_auto_20170526_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechahora',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='fechahora',
            name='hora_actual',
            field=models.CharField(default=datetime.datetime(2017, 5, 26, 22, 51, 20, 851000), max_length=200),
        ),
    ]
