# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horactual', '0004_auto_20170526_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechahora',
            name='hora_actual',
        ),
    ]
